# Generated by Django 3.1.13 on 2021-09-25 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(choices=[('PR', 'Pruning'), ('HA', 'Harvest'), ('SC', 'Scouting'), ('OT', 'Other')], default='OT', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
