# Generated by Django 3.1.13 on 2021-09-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210925_0601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldworker',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
